#print("Hello World!")
#print("Hello Again")
print("I like typing this.")
#print("This is fun.")
#print('Yay! Printing')
#print("I'd much rather you 'not'.")
#print('I "said" do not touch this.')
#print ("hey I added another line!")
#print ("I wish all of programmming was as easy as this")
#print("E x AC t l Y! What I A M 2343567543 typing here???")